project:
  type: website

website:
  title: "Nancy Salazar"
  
  navbar:
    background: secondary
    search: true
    left:
    #Differnt website pages
      - href: index.qmd
        text: Home
      
      - href: about.qmd
        text: Projects
     

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

